version: '3.9'
services:
  db:
    image: postgres:14-alpine
    container_name: stock_db
    ports:
      - 5432:5432
    volumes:
      - ./.tmp/postgres:/var/lib/postgresql/data
    networks:
      - stock-network
    environment:
      PGUSER: $POSTGRES_USER
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 5s
      timeout: 3s
      retries: 5
  redis:
    container_name: stock_redis
    image: redis:6.2-alpine
    volumes:
      - ./.tmp/redis:/data
    networks:
      - stock-network
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 5s
      timeout: 3s
      retries: 5
networks:
  stock-network:
    driver: bridge
